---
inherit_from:
  - .rubocop_todo.yml
  - .rubocop_dnsimple.yml

require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'vendor/**/*'
